@startuml
|kunde|
start
:gå til website;
|#AntiqueWhite|website|
:login;
|kunde|
:bestil cupcakes;
|website|
:gem ordre i database;
:send kvittering;
fork
|kunde|
:kvittering]
:afhent cupcakes;
fork again
|butik|
:bag cupcakes;
end fork
:Cupcakes]
stop
@enduml
